### ISSUE TITLE
Typo "On the first level, the keys are...." sentence. 2nd name  should be "Freddy Mercury"

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/nested-hash-iteration#9]
Jon Snow:      
{ :name=>"Jon", 
  :email=>"jon_snow@thewall.we", 
  :favorite_ice_cream_flavors=>["chocolate", "vanilla", "mint chip"],
  :knows=>nil
}
 
Freddy Mercury: 
{ :name=>"Freddy", 
:email=>"freddy@mercury.com", 
:favorite_ice_cream_flavors=>["strawberry", "cookie dough", "mint chip"]
}
On the first level, the keys are our contacts' names, "Jon Snow" and "Freddy", and our values are the hashes that contain a series of key/value pairs describing them.

**Comment by jenmyers** [comment]
Fixed in commit 6385a8d64752000c2470a29ea66dfe9fe0b2a7a9
